### ISSUE TITLE
Exceptions not logged if message is empty

### ISSUE THREAD

**Issue by houbi56** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#104]
If an empty message is supplied with an exception, the logging is not performed.

**Comment by houbi56** [comment]
Would it possible to get some attention on this? :) 
Seems rather serious that logging is not performed on exceptions if there's no msg..
There's an available pull request..

**Comment by huorswords** [comment]
Hi @houbi56 ,

I'm sorry by the delay. Too much work on latest months...

You will found your PR committed into version 5.0.3, published yesterday to nuget.org.

Thank you very much by your contribution. 🙂
