### ISSUE TITLE
Use this package in .net 5 console application

### ISSUE THREAD

**Issue by Timo-Weike** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#108]
Is the part AspNetCore in the name only so people can finde it easier or does this package has real dependencies to any AspNetCore-Packages or the runtime?

**Comment by huorswords** [comment]
Hi @Timo-Weike,

No, the AspNetCore in the name is only because the name without it was taken when I have created it.

The only dependencies are Microsoft.Extensions.Logging and the log4net libraries.
