### ISSUE TITLE
Removing old log files

### ISSUE THREAD

**Issue by DanBrk** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#115]
Removing log files older than N days cannot be done in log4net.

Is there an option to modifying the logging behavior so that it will automatically remove log files older than N days?

**Comment by huorswords** [comment]
Hi @DanBrk, do you have this problem also using Log4net without Microsoft.Extensions.Logging.Log4Net.AspNetCore library? If so, maybe yo need to open this issue there, as this package is not official from log4net team or Microsoft.
