### ISSUE TITLE
.net 7

### ISSUE THREAD

**Issue by greengumby** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#129]
Will this project be updated to support .net 7 ?

**Comment by hl-tommi** [comment]
> Will this project be updated to support .net 7 ?

Does it not work in .Net 7.0?

I think this project as distributed as a .NET Standard 2.1 API. And if that's the case, then that would, at least in theory, make it compatible with .Net 7.0.

**Comment by huorswords** [comment]
Available at [7.0.0](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/releases/tag/7.0.0)
