### ISSUE TITLE
Modify configuration at runtime?

### ISSUE THREAD

**Issue by steven-gruverman** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#14]
For security reasons, we do not include our DB connection string for ADONetAppender in log4net.config. I extended ILoggerFactory with a wrapper around a Log4NetProvider constructor:
[CustomLog4NetExtension.txt](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/files/1803814/CustomLog4NetExtension.txt)

And extended Log4NetProvider with a method that sets the connection string in a way that we had working with straight log4net:
[CustomLog4NetProvider.txt](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/files/1803823/CustomLog4NetProvider.txt)

The we in Startup.cs in the Configure method we do this:
loggerFactory.AddLog4NetWithAdoConnectionString( GetLoggingConnectionString()) ;

It looks like this succeeds in updating the Repository but the ADONetAppender does not work - and it does work if we include the same connection string in log4net.config.

We already thank you for the work you did in making this package available.
If you can point out mistakes I'm making or suggest a better way, that would be much appreciated, too.

Thanks,
Steve Gruverman

**Comment by huorswords** [comment]
Hello @steven-gruverman ,

Thank you by your question.

I will take a deeper look on your question as soon as possible, but I can tell you that, in my case, when I have to change the connection string for a given environment on the log4net.config file, as I have a CI/CD pipeline configured, I have an step that set up the proper connection string on the file when the application is on deployment process.

I come back to you when I can check your fork (I think you have the whole code on there) and I will try to answer you.

Thank you again.

Regards

**Comment by steven-gruverman** [comment]
Hello,

Thank you for your reply. I don’t think it is a good use of time to work on this issue: A user on StackOverflow pointed out this page:
https://logging.apache.org/log4net/release/framework-support.html#Appenders

The appender we’re trying to use isn’t supported by log4net when using .NetCore Standard 2.0!

So we might be able to get this to work, perhaps with your help, but I think we need to find a new approach to how we do logging

I don’t think I have a fork – I just cloned the repo so I could understand how to extend the code without changing it. (But I’m kind of a Github newbie).

Thanks again for taking a look at this issue.

Steve Gruverman | Application Developer II
IDEXX Laboratories, Inc. | Steven-Gruverman@idexx.com<mailto:Steven-Gruverman@idexx.com>
Phone: + 1 207 556 6981
Mobile: + 1 207 798 2893

**Comment by huorswords** [comment]
Hi,

Oh! I confuse your case with a fork that I see some days ago... Sorry for that.

Maybe, if you want to do it, you can implement your own custom Log4Net appender using ADO or EF. You only need to inherit from `AppenderSkeleton` class and implement `ActivateOptions`, `Append`,  `Flush` and `OnClose` methods.

It is a little more complex that use an out of the box appender, but Log4Net is so flexible to allow you to create your custom appender from zero.

Reference: https://jonhilton.net/2008/07/23/log4net-custom-appender/

I will close this issue if you don't have any inconvenient, then...

Thank you again.

Regards,

**Comment by steven-gruverman** [comment]
Thank you for your suggestion and related information!
Yes, fine if you close the issue.

Steve Gruverman | Application Developer II
IDEXX Laboratories, Inc. | Steven-Gruverman@idexx.com<mailto:Steven-Gruverman@idexx.com>
Phone: + 1 207 556 6981
Mobile: + 1 207 798 2893
