### ISSUE TITLE
Invalid exception logging

### ISSUE THREAD

**Issue by cezarypiatek** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#15]
Is there any reason why exception object is not passed directly into log4net methods? I'm talking about this method https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/blob/e685ff7c4071c87b356b69d4a8f005b6a726f3ef/src/Microsoft.Extensions.Logging.Log4Net.AspNetCore/Log4NetLogger.cs#L80

Instead of passing exception into log4net method it is merged into message variable. It causes issues with layouting log entry and parsing log messages (I'm not able to separate log message from exception stacktrace)

**Comment by huorswords** [comment]
Hello @cezarypiatek ,

No, it is not a justified reason, it is only a business decission when I adapted the original version of the Logger implementation.

Sorry by my ignorance, but do you have any example of what you are expecting for in order to be able to sepparate log message from the exception stack trace?

Thank you. Regards,

**Comment by cezarypiatek** [comment]
hi @huorswords 

Thanks for replay. Log4net has a few conversion patterns (such as %exception, %stactrace, %stactracedetail) which are not populated when you omit the exception argument in logging method. You can read more about these conversion patters here https://logging.apache.org/log4net/log4net-1.2.13/release/sdk/log4net.Layout.PatternLayout.html

When the exception is not merged into single message field I can separated message from the stacktrace on the layout pattern level and use it later for log parsing.

**Comment by huorswords** [comment]
Hello @cezarypiatek ,

Thank you by your explanation.

I have pushed a branch https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/tree/feature/15 that includes a simple test to check how the exception stacktrace is formatted using pattern layout. But unfortunately, I am not able to configure it properly to use the stacktrace pattern...

Can you check out the branch and let me know if I'm missing something?

Thank you.

**Comment by cezarypiatek** [comment]
@huorswords  I will check that later

**Comment by cezarypiatek** [comment]
I have no idea why `StackTracePatternConverter` is not working but the stacktrace can be obtained using `ExceptionPatternConverter` with stacktrace parameter as follows

```xml
<layout type="log4net.Layout.PatternLayout">
    <conversionPattern value="%level %thread - STACK: %exception{stacktrace} - MESSAGE: %message%newline" />
</layout>
```
I've tested it with your UT and it seems to work

`ExceptionPatternConverter` has the following options:
- message
- source
- helplink
- stacktrace

**Comment by huorswords** [comment]
Hello @cezarypiatek ,

Thank you by your help & suggestions.

I have merged the changes on branch feature/15 into develop and master, and deploy the resulting nuget package into nuget.org.

Now, the Exception Pattern converter should be available and working properly throught the log4net logger on the nuget package.

Regards
