### ISSUE TITLE
Not compatible with new WebHostBuilder pattern

### ISSUE THREAD

**Issue by twenzel** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#20]
With Asp.net Core 2.0 the recommend logging configuration was moved from Startup.cs to Program.cs.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#how-to-add-providers.

So unfortunately, this is not working:
```
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureLogging(builder =>
                {
                    builder.AddLog4Net("log4net.config");
                })
                .Build();
```

**Comment by huorswords** [comment]
Hello @twenzel,

Thank you very much by your work.

I have reopened the issue until it is merged into master and deployed to the nuget.org service.

I will close it when the changes will be released.

Thank you again. Regards.

**Comment by huorswords** [comment]
Hello @twenzel ,

I have included your changes into the develop & master branches, and deployed the nuget into  nuget.org. The release version is 2.1.0.

Thank you very much by your collaboration, again. :)
