### ISSUE TITLE
Trying to log to sql server

### ISSUE THREAD

**Issue by Outerphase** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#22]
I've got my log4net.config to only contain the DebugAppender and the AdoNetAppender:
<?xml version="1.0" encoding="utf-8" ?>
<log4net debug="true">
  <root>
    <level value="ALL"/>
    <appender-ref ref="AdoNetAppender"/>
    <appender-ref ref="DebugAppender" />
  </root>
  <appender name="DebugAppender" type="log4net.Appender.DebugAppender" >
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%date [%thread] %-5level %logger ---- %message%newline" />
    </layout>
  </appender>
  <appender name="AdoNetAppender" type="log4net.Appender.AdoNetAppender">
    <bufferSize value="1" />
    <threshold value="ALL"/>
    <connectionType value="System.Data.SqlClient.SqlConnection, System.Data, Version=1.0.3300.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <connectionString value="BLABLA" />
    <commandText value="dbo.p_LogApplication_InsertEmpty"/>
    <commandType value="StoredProcedure"/>
  </appender>
</log4net>

I setup the Log4Net.AspNetCore as the normal in the Startup.cs class
  loggerFactory.AddLog4Net("log4net.config");

And then in the Controller constructor its expecting the log4net.Core.ILogger:
...
	private readonly log4net.Core.ILogger _logger;
	public ValuesController(log4net.Core.ILogger logger)
	{
		//log4net.aspnetcore 2.0
		_logger = logger;
		_logger.Log(new LoggingEvent(new LoggingEventData() { Message = "NewTest", LoggerName = "Main", Level = Level.Info }));
...

When the app starts up the following is always displayed and the AdoNetAppender doesn't load:

log4net:ERROR [AdoNetAppender] ErrorCode: GenericFailure. Failed in DoAppend
System.TypeLoadException: Could not load type 'System.Runtime.Remoting.Messaging.CallContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at log4net.Util.LogicalThreadContextProperties.GetLogicalProperties()
   at log4net.Util.LogicalThreadContextProperties.GetProperties(Boolean create)
   at log4net.Core.LoggingEvent.CreateCompositeProperties()
   at log4net.Core.LoggingEvent.CacheProperties()
   at log4net.Core.LoggingEvent.FixVolatileData(FixFlags flags)
   at log4net.Appender.BufferingAppenderSkeleton.Append(LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.DoAppend(LoggingEvent loggingEvent)

Also of note is the AdoNetAppender is calling the sproc with no parameters. Any assistance would be helpful.

Thanks!
-jason

**Comment by huorswords** [comment]
Hello @Outerphase ,

Sorry, but searching for your error, seems that the AdoNetAppender is not supported on .NET Standard 1.3, and not specifically supported on .NET Core 1.x / 2.x.

You can check the compatibility table on the next URL: https://logging.apache.org/log4net/release/framework-support.html#Appenders

You also can check the specific problems with AdoNetAppender reported by the users on the Apache Log4Net Jira: https://issues.apache.org/jira/browse/LOG4NET-531?jql=text%20~%20%22AdoNetAppender%22

Regards
