### ISSUE TITLE
Adding this library to Log4net

### ISSUE THREAD

**Issue by saeidehv** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#23]
Hi,

Thank you for your work, I was wondering do you have any plan to contribute this extension through pull request to log4net library?

Thanks,

**Comment by huorswords** [comment]
Hello @saeidehv ,

Thank you very much by your question.

Sincerely... no, I don't plan to contribute to log4net library with this project.

In fact, I see it most suitable to be part of [aspnet/Logging](https://github.com/aspnet/Logging) repository.

My intention is not to pull the code into any of those repositories while I'm able to mantain this one. At the moment that I couldn't mantain the code, mine or from contributors, I'll consider seriously to move it into a larger repository, as I think that is been helpful for lot of people and I don't want to be discontinued.

Thank you again. Regards.
