### ISSUE TITLE
Support for configuration watching

### ISSUE THREAD

**Issue by DvirL** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#24]
Hi,

Is there a possibility to support the configuration watcher?
I think you just need to replace the call for Configure function with ConfigureAndWatch.

Thanks

**Comment by huorswords** [comment]
Hello @DvirL ,

Thank you very much by your request.

Could it be acceptable to you to provide an override of the constructor that accepts a boolean argument that indicates it should watch or not?

Of course, this change will include the corresponding override of the extension method to indicate this argument also. By default, the behavior will be not to watch for changes.

Let me know your thoughts on this.

Thank you again.

**Comment by chanjunweimy** [comment]
I tried to implement this on my fork too. Furthermore, I have written code to support change of parameters in the code during startup. It is shown in PR #26

**Comment by huorswords** [comment]
Hello @DvirL,

I have included watching options on develop branch, as now you can do next:

`factory.AddLog4Net("log4net.config", true)`

Waiting for the @chanjunweimy PR to be reviewed, this will be merged into master as soon as possible.

Regards
