### ISSUE TITLE
ExtensionMethod to allow CreateLogger<T> for owning class

### ISSUE THREAD

**Issue by izzycoding** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#25]
I am wondering if something like the following would work so I can depend on the ILogProvider in my class and manually create a logger for the given type.

`
public static ILogger CreateLogger<T>(this ILoggerProvider provider)
    where T : class
{
    return provider.CreateLogger(typeof(T).AssemblyQualifiedName);
}
`

This would allow me to configure different settings for the different loggers (I could be missing something that is already built in-to the Logging framework).

**Comment by huorswords** [comment]
Hello @izzycoding ,

Sorry by the delay in anwering you. 

Can you give me a minimum test case in order to figure out what is your exact expectation?

Thank you.
