### ISSUE TITLE
any chance to support .Net Standard?

### ISSUE THREAD

**Issue by shazha** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#3]
log4net supports .NET Standard 1.3 since v2.0.6. However when I install this extension from NuGet, the following error message is shown:
`Package Microsoft.Extensions.Logging.Log4Net.AspNetCore 1.1.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.Extensions.Logging.Log4Net.AspNetCore 1.1.0 supports: netcoreapp1.1 (.NETCoreApp,Version=v1.1)`

**Comment by huorswords** [comment]
Hello @shazha ,

Thank you very much by be interested on this project.

About your question... What is your goal to add this nuget package into a .NET Standard project?

I mean, the nuget itself is designed to allow the developer to use log4net as .NET Core logging provider, without worrying about how the .NET Core Logger Factory and the pipeline works.

* [Logging on .NET Core documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x)

Can you please share with me your thoughts on this, or the scenario where you want to include the package?

Regards,

**Comment by shazha** [comment]
@huorswords ,
I'm building a .net standard-targeted library and would like to use log4net for internal logging. You just remind me that I'm only supposed to use .Net Core Logger Factory for .net core projects and what I asked for doesn't make any sense. I think using log4net APIs directly is enough for me so far.
Feel free to close this issue directly.
Thanks,

**Comment by huorswords** [comment]
Hello @shazha,

Thank you by your answer.

So, as you agree with it, I close this issue.

Keep me posted whether you will find anything else when you will work on a .net core targeted application.

Regards!
