### ISSUE TITLE
Saving Log files to azure blob

### ISSUE THREAD

**Issue by harishkakani** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#36]
Is there way to save log files to Azure blob storage using this package. If yes, can you please share configurations.

**Comment by huorswords** [comment]
Hello @harishkakani ,

Thank you for your question about Microsoft.Extensions.Logging.Log4Net.AspNetCore.

You are asking for an appender implementation for Azure Storage, but this project only pretends to cover the connection between Microsoft Logging Framework with the Log4Net library.

I have search github looking for a repository where someone created this appender, but after a quick search, I didn't found any (I have found only some compatible with .NET Framework, not with .NET Core).

So, I'm sorry but... I can't help you with that.

Regards

**Comment by harishkakani** [comment]
Thanks for inputs @huorswords
