### ISSUE TITLE
Dotnet Core 2 issue with log4net 2.0.8 dll

### ISSUE THREAD

**Issue by DonkeyDarbie** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#40]
Hi Guys
I import the reference to the application in my client.  The client complains that it cant find log4net 2.0.8.

The problem is the 2.0.8 dll is .net framework DLL.  It wont run in a linux container.  So if your trying to create a docker Linux container application your stuffed.

Arent you?

Regards
Donks

**Comment by huorswords** [comment]
Hello @DonkeyDarbie ,

I have been testing the build process using a linux virtual machine and I found an error related to the .NET Framework 4.6.2 compatibility on this linux machine.

I will test the nuget import directly on a linux docker container as soon as I can to review your specific problem.

I'll be back to you with my results ASAP.

**Comment by huorswords** [comment]
Hello again @DonkeyDarbie ,

I have pushed a sample application ready to be started as a linux docker container. I also have tried it on my local and seems that is working properly, without problems.

Let me know if you have any problem with that.

Thank you.

**Comment by DonkeyDarbie** [comment]
Hi Angel

Thanks for the help. I shall let you know how I get on.

Regards
Donks

**Comment by huorswords** [comment]
Hi @DonkeyDarbie ,

Any news about that?

Thank you.

**Comment by DonkeyDarbie** [comment]
Hi Angel

Not yet, up to me neck in Angular at the mo.
I shall have to get back to you.

Sorry.
Donks

**Comment by huorswords** [comment]
Hello @DonkeyDarbie ,

I need confirmation from you that everything is working on your environment within the dockerized test project that I have provided.

Meanwhile, I will close this issue until you will be able to test and get back with results.

Sorry by the inconveniences.

**Comment by DonkeyDarbie** [comment]
Hi Angel

Yes I promise I shall do.

It has an IP address smack in the default Docker image range.  I have to
fix that to get out.

Regards
Derek
