### ISSUE TITLE
Aspnetcore2.0 Web Application Failed to Log

### ISSUE THREAD

**Issue by chanjunweimy** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#41]
I would like to report an issue (which may or may not be the bug of this extension, I am not really sure, but I tried other open source logging extension ([Serilog](https://github.com/serilog/serilog-aspnetcore)) that has no issue with this setup before).

- Background
I was trying to inject log4net for a project based on [identity server](http://docs.identityserver.io/en/release/topics/logging.html?highlight=logging) but failed.

- What is exactly the issue?
I have setup a web project running on  `netcoreapp2.0` framework and setup log4net using the extension method provided in `Microsoft.Extensions.Logging.Log4Net.AspNetCore nuget` but have failed to log some messages. 

- How to reproduce?
I have setup a minimal `netcoreapp2.0` project to reproduce the issue, please kindly navigate to [log4netaspnetcoretest](https://github.com/chanjunweimy/log4netaspnetcoretest/tree/master/NetCoreWebApplication) (https://github.com/chanjunweimy/log4netaspnetcoretest/tree/master/NetCoreWebApplication). Follow the instruction in README.MD to reproduce the issue.

- So what happened?
I expect the log.txt to have the log message I added but it does not contain those.

Thank you.

Jun Wei

**Comment by huorswords** [comment]
Hello @chanjunweimy ,

This behavior had been detected by @murraywsmith (thank you very much again!) on issue #34 . 

His approach to resolve the issue is to change your `BuildWebHost` method implementation in order to set up the minimum allowed log level into the ASP .NET Core 2 logging service.

```csharp
public static IWebHost BuildWebHost(string[] args) =>
	WebHost.CreateDefaultBuilder(args)
		.UseStartup<Startup>()
		.ConfigureLogging((hostingContext, logging) =>
		{
			logging.AddLog4Net();
			logging.SetMinimumLevel(LogLevel.Debug);
                        // The ILoggingBuilder minimum level determines the
                        // the lowest possible level for logging. The log4net
                        // level then sets the level that we actually log at.
		})
		.Build();
```

I have tested this solution on my computer in your project, but... Can you confirm if this change solves your issue?

Thanks.

**Comment by chanjunweimy** [comment]
Hello @huorswords ,

Thanks for your prompt reply. Ah I see, yes, it indeed solves the issue of this project... Let me try it out in the identity server project before closing this issue. I will inform you ASAP. Thanks a lot again!  

In this case, should we add this solution into the readme?

Thank you.

Regards, 
Jun Wei

**Comment by chanjunweimy** [comment]
Hello @huorswords , 

Thanks a lot. I have verified that it is working. ^^

Regards,
Jun Wei

**Comment by huorswords** [comment]
Good idea! Done!

https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/blob/develop/README.md
