### ISSUE TITLE
"Overwriting the native log4net xml configuration using the Net Core configuration system" is case sensitive.

### ISSUE THREAD

**Issue by chanjunweimy** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#42]
What is the problem?
- Expected "overrided.log" (Overided in appsettings.json) to be generated but "log.txt" (specified in log4net.config) is the one that is generated.

How to reproduce?
- Run this project: https://github.com/chanjunweimy/log4netaspnetcoretest

What is the reason?
- I figured out the issue is because when setting attribute value, the attribute key is case sensitive.

If case sensitive is the design, then
- I would suggest updating README.md to:
``json
"Log4net": [
  {
    "XPath": "/log4net/appender[@name='RollingFile']/file",
    "Attributes": {
      "value": "overrided.log"
      }
    },
    {
      "XPath": "/log4net/appender[@name='RollingFile']/maximumFileSize",
      "Attributes": {
        "value": "1024KB"
      }
    }
]
``

**Comment by huorswords** [comment]
Hello @chanjunweimy ,

Thank you again by opening this issue.

I have created a fix, that will be available on next release of the nuget package, that avoids the case sensitive problem that you point out on this issue.

You could find the fix, until the code is merged, on the develop branch. Feel free to test it at tell me if it solves your specific problem.

Regards,
