### ISSUE TITLE
Add .Net Framework versions to nuget

### ISSUE THREAD

**Issue by lawrences-racti** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#5]
Since .Net Framework packages built with 4.6.1+ can use .Net Core (2.0) packages, can you add additional supported versions to the csproj. I have cloned this project and just changed the csproj <TargetFramework> element to <TargetFrameworks>netcoreapp2.0;net462</TargetFrameworks> - this seems to work. We have some third-party libraries that are only .Net Framework so we need to create libraries but still support .Net Core Logging.

**Comment by huorswords** [comment]
Hello @lawrences-racti,

A new nuget package version has been uploaded to nuget.org in order to be compatible with these target frameworks:

.NET Core 1.1
.NET Core 2.0
.NET Framework 4.6.2.

Thank you by your suggestion.

Regards,
