### ISSUE TITLE
How to access this from WCF

### ISSUE THREAD

**Issue by shah-keyur** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#50]
Hi ,

 I have created a class library project where I am using this package and I can consume that class library project from.Net core application.

However, I want to access the same class library project from WCF. how can I configure ILogger from WCF service using this package?

Appreciate your help.

Thanks,
Keyur

**Comment by huorswords** [comment]
Hello @shah-keyur ,

Sorry, I have not integrated never this nuget package within a WCF service.

But googling some time, I found a post that maybe will be helpful for you: 

https://www.milestonetg.com/blog/development/2018/02/17/adding-new-microsoft-extensions-to-legacy-wcf-and-asmx-web-services.html

I agree with the post owner: You can just set up the ILogger into your dependency injection container and use it from the corresponding class where you want to log.

Regards.

**Comment by shah-keyur** [comment]
Thanks,

You can close this now.
