### ISSUE TITLE
Error when format log string

### ISSUE THREAD

**Issue by miaodadao** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#52]
`LogInformation("{2}{1}{0}{2}", 0, 1, 2)` will throw an `AggregateException` exception.

> System.AggregateException: An error occurred while writing to logger(s). (Index (zero based) must be greater than or equal to zero and less than the size of the argument list.) 

The inner string format method shouldn't check `args`'s number just by `{*}`'s number simplely.

UnitTest Code:

``` C#
[TestMethod]
//[ExpectedException(typeof(AggregateException))]
public void TestFormatBug()
{
	var factory = new LoggerFactory();
        Assert.IsTrue(File.Exists("log4net.xml"));
	factory.AddLog4Net("log4net.xml");
	var log = factory.CreateLogger("");
	log.LogInformation("{0}{0}", "OK"); // 应该是用{*}的个数直接和后面参数的个数比较了
}
```

**Comment by huorswords** [comment]
Closing this bug as it is reproduced on the [aspnet/Logging](https://github.com/aspnet/Logging/issues/907) repository.

**Comment by huorswords** [comment]
@miaodadao as per reference on https://github.com/aspnet/Logging/issues/907#issuecomment-433181733, the behavior is As-Designed, so will not be fixed until the aspnet/Logging team works on it.
