### ISSUE TITLE
Cant load the log4net config file from the project root

### ISSUE THREAD

**Issue by korxaq** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#53]
Hello!

   I just upgraded to version 2.2.6 from 2.2.5 and had to downgrade as I am getting an error now finding the log4net config file 

System.IO.FileNotFoundException: 'Could not find file 'C:\Users\jsoto\Documents\MicroServices\BonusesPlayerMicroservice\BonusesPlayer\BonusesPlayer.Api\bin\Debug\netcoreapp2.1\log4net.config'.'

The file location is on the project root 
C:\Users\jsoto\Documents\MicroServices\BonusesPlayerMicroservice\BonusesPlayer\BonusesPlayer.Api\

But for some reason now its looking in the bin\Debug\netcoreapp2.1 folder

and I just have in my startup file the no parameters add log 4 net instruction

loggerFactory.AddLog4Net();

with just downgrading from 2.2.6 to 2.2.5 the issue disappear

using dotnet verion 2.1.1

Thanks a lot!

**Comment by huorswords** [comment]
Hello @korxaq ,

Sorry by the delay answering you.

Yes, the behavior to load the log4net.config file have been changed to support the new coming features on IIS Express for .NET Core 2.2, and now is looking for the file in the folder where your application is located.

Could you try to set the property named **Copy to Output directory** for log4net.config file to **Copy always**?

Thank you. Regards.

**Comment by huorswords** [comment]
Hello @korxaq ,

Have you tried my last comment proposal?

Thank you.

**Comment by korxaq** [comment]
@huorswords Thanks for the answer! I will try this tomorrow for sure and will let you know how it went

Thanks a lot!

**Comment by huorswords** [comment]
Any news @korxaq? 

I will close the issue and, if you cannot fix the situation using my suggestion, please feel free to open it again and let me know why is not working.

Thank you.

**Comment by korxaq** [comment]
Its working with the Copy always option, thanks!
