### ISSUE TITLE
log4net.Appender.RollingFileAppender log file isn't created with TargetFramework netcoreapp2.2

### ISSUE THREAD

**Issue by Iamcerba** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#55]
Hello,

It is revealed that with new .NET Core 2.2 log file isn't created while using RollingFileAppender.

You can reproduce this scenario even in your Sample.WebApi_NetCore22 example by updating packages to 2.2 release version.

**Comment by Iamcerba** [comment]
@huorswords,

Seems it's created in different location: C:\Program Files\IIS Express\example.log

**Comment by Iamcerba** [comment]
@huorswords,

Seems it is something that couldn't be resolved on your side.

More details: https://github.com/aspnet/AspNetCore/issues/4206

The only workaround which I see now (**if we want to use InProcess hosting model**) is to update Environment.CurrentDirectory variable **before** log4net initialization:

```csharp
Environment.CurrentDirectory = "<correct path>";

loggerFactory.AddLog4Net();
```

The following helper could be used for this: https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module/samples_snapshot/2.x/CurrentDirectoryHelpers.cs

**Comment by huorswords** [comment]
Hello @Iamcerba ,

Thank you very much by all of this information. Will be very helpful to me in the future.

Let's wait then until the Microsoft team fix the issue on ASPNetCore project.

Do you prefer to get this issue open until this or maybe it can be closed?
