### ISSUE TITLE
Logging in two different files on demand

### ISSUE THREAD

**Issue by sylendra7** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#56]
Hi,

How to logging in two different files on demand.Let say I want to log data in Login action method in one file and want to log another action methods data in another file from the below lines of code.

_logger.LogInformation("Login Action Calling");====> This has to log in one file 

_logger.LogInformation("Employee Edit Action Calling");====> This has to log in another file

**Comment by huorswords** [comment]
Hello @sylendra7,

This scenario can be fulfilled using the configuration options from log4net, and using different loggers for each desired log file.

Please review the official documentation on https://logging.apache.org/log4net/release/manual/configuration.html .

I have not tested it, but should be something similar to...
```csharp
//...
var logger1 = log4netProvider.CreateLogger("File1");
var logger2 = log4netProvider.CreateLogger("File2");

logger1.LogInformation("This message will be shown on File1");
logger2.LogInformation("This message will be shown on File2");
```
And the log4net.config file...
```xml
<log4net>
    <appender name="RollingFile1" type="log4net.Appender.RollingFileAppender">
        <file value="File1.log" />
        <appendToFile value="true" />
        <maximumFileSize value="100KB" />
        <maxSizeRollBackups value="2" />
 
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%level %thread %logger - %message%newline" />
        </layout>
    </appender>
    <appender name="RollingFile2" type="log4net.Appender.RollingFileAppender">
        <file value="File2.log" />
        <appendToFile value="true" />
        <maximumFileSize value="100KB" />
        <maxSizeRollBackups value="2" />
 
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%level %thread %logger - %message%newline" />
        </layout>
    </appender>
    
    <root>
        <level value="DEBUG" />
    </root>
    <logger name="File1">
        <appender-ref ref="RollingFile1" />
    </logger>
    <logger name="File2">
        <appender-ref ref="RollingFile2" />
    </logger>
</log4net>
```

Let me know your thought on this after you can review the documentation. Thank you.

**Comment by sylendra7** [comment]
Okay Thanks @huorswords . Can you please tell me how to log only my logs ,because it is logging extra logs like 

Executing RedirectResult, redirecting to /Home/Index.
 Request successfully matched the route with name 'default' and template '{controller=Login}/ etc

**Comment by huorswords** [comment]
You can avoid to include the built-in messages from ASP.NET Core removing it from the logging system itself as follows:
```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
	WebHost.CreateDefaultBuilder(args)
		.ConfigureLogging((hostingContext, logging) =>
		{
			logging.AddFilter("Microsoft", LogLevel.None);
		})
		.UseStartup<Startup>();
```
This snippet, located on `Program.cs` file, indicates to the logging system that all the Microsoft events should be ignored.

If this radical approach doesn't match your requirements, then you can use directly the filters available on the log4net library (https://logging.apache.org/log4net/release/manual/configuration.html#Filters) in order to configure the appenders to only process the events that you want to process. This last option is more natural to me.
