### ISSUE TITLE
Add support for net standard 2.0

### ISSUE THREAD

**Issue by tcz717** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#6]
Thanks for you nice lib. I am trying to use your lib in a net standard 2.0 project. However nuget prevents me install this lib because not support standarn 2.0.

So could you please add `netstandard2.0` to solve it?
https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/blob/45a6e11590ea1027b516f0e664001146b7f89837/src/Microsoft.Extensions.Logging.Log4Net.AspNetCore/Microsoft.Extensions.Logging.Log4Net.AspNetCore.csproj#L3

And happy new year

**Comment by huorswords** [comment]
Hello @tcz717 ,

Thank you very much by your kindly words.

Can you explain me something about the scenario that you are trying to solve with this nuget package?

For me, your question is similar to #3, and I think that the answer could be the same, but I want that, if you can, expose me the scenario in order to evaluate if the .net standard support is reasonable or not.

Thank you very much.

Regards

**Comment by tcz717** [comment]
Hi @huorswords

I am writing a RPC lib in .net standard 2.0 and its network part is based on [DotNetty](https://github.com/Azure/DotNetty). `DotNetty` has an internal logging system that supports `Microsoft.Extensions.Logging.ILoggerFactory ` interface, but my whole system uses `log4net` to log. So I need an adapter to connect these two parts.

Thanks for your reply.

**Comment by huorswords** [comment]
Hello @tcz717,

After reviewing your request, and after checking some of the other Logging providers that also supports Microsoft.Extensions.Logging library, I have just included .NET Standard 2.0 as supported target framework of this project.

The nuget package will be available soon on nuget.org.

Thank you very much by your suggestion.

Regards.

**Comment by dgxhubbard** [comment]
I just checked nuget and .net standard 2.0 is not list as a supported framework.
Do yo know when this release will be available?
Thanks

**Comment by huorswords** [comment]
Hello @dgxhubbard,

Sorry but, on last version of the nuget package, .Net Standard 2.0 is one of the dependencies...

Where have you checked it? From VS? From nuget.org portal?

Thank you. Regards.

**Comment by dgxhubbard** [comment]
I opened the manage nuget packages for solution click on browse and type in "log4net"
The last one listed is .net standard 1.3

**Comment by dgxhubbard** [comment]
I see the problem. I searched here found log4net and thought this was log4net. I looked at the logging extension and there is a .net standard 2.0. Alas, I was looking for log4net thought.
Sorry about that.

**Comment by huorswords** [comment]
Oh! I see...

Cool, I have worried about it. :)

Anyway, thank you by your question.

**Comment by JensFu** [comment]
Hi, I just tried to add the log4net nuget for a netstandard2.0 library and had the same problem like dgxhubbard. What is excatly the name i have to search for in the nuget package manager of visual studio?

**Comment by huorswords** [comment]
Hello @JensFu ,

The official **log4net** nuget package (https://www.nuget.org/packages/log4net/) it is compatible with .NET Standard 1.3, so it should be compatible with any library created on .NET Standard 2.0.

At the other hand, the Microsoft.Extensions.Logging.Log4Net.AspNetCore package it is compatible with .NET Standard 2.0, and imports automatically the reference from log4net v.2.0.8 package.

Please, let me know any thought on this.

Thank you.

**Comment by Vycka** [comment]
Well it looks like I'm not able to use custom layout having code available only in .NET Standard 2

Is there any plans to eventually do proper .NET Standard 2.0 support or I'm better off by looking for alternative logging solutions?

**Comment by petertsu** [comment]
Once you add the log4net  reference to .NETStandard 2.0 project you get a lot of nu1605 warnings

https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(NU1605)%26rd%3Dtrue

I think there a need to make log4net .NETStandard 2.0 compatible

**Comment by huorswords** [comment]
Completely agree @petertsu , but unfortunately log4net is a "third-party" library on this project.

Maybe you can propose it as an enhancement on the log4net repo: https://github.com/apache/logging-log4net.

**Comment by JensFu** [comment]
Ich kehre zurück am 20.02.2019.

Danke für Ihr Mail.
Ich bin momentan nicht im Büro erreichbar und beantworte Ihre Nachricht
schnellstmöglich nach
meiner Rückkehr.

Wenden Sie sich in dringenden Fällen an:
Cesar Schaehle / cesar.schaehle@regatron.ch / 071 846 69 03

Vielen Dank für Ihr Verständnis
Freundliche Grüsse
Jens Füllemann


Thank you for your email.
I am currently out of the office, but will reply to your message as soon as
possible once i get back.

For immediate assistance, please contact:
Cesar Schaehle / cesar.schaehle@regatron.ch / 071 846 69 03
Thank you for your understanding.
Kind regards,
Jens Füllemann


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore] Add support
for net standard 2.0 (#6)" gesendet am 19.02.2019 13:33:28.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by JensFu** [comment]
Ich kehre zurück am 20.02.2019.

Danke für Ihr Mail.
Ich bin momentan nicht im Büro erreichbar und beantworte Ihre Nachricht
schnellstmöglich nach
meiner Rückkehr.

Wenden Sie sich in dringenden Fällen an:
Cesar Schaehle / cesar.schaehle@regatron.ch / 071 846 69 03

Vielen Dank für Ihr Verständnis
Freundliche Grüsse
Jens Füllemann


Thank you for your email.
I am currently out of the office, but will reply to your message as soon as
possible once i get back.

For immediate assistance, please contact:
Cesar Schaehle / cesar.schaehle@regatron.ch / 071 846 69 03
Thank you for your understanding.
Kind regards,
Jens Füllemann


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore] Add support
for net standard 2.0 (#6)" gesendet am 19.02.2019 14:00:15.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by IqraMunir5** [comment]
Hi, I have been trying to deploy web API on Lambda AWS but every time I get this error in publishing on AWS.  error NU1605:  log4net 2.0.8 -> System.Net.Sockets 4.1.0 -> runtime.unix.System.Net.Sockets 4.3.0 -> System.Net.Primitives (>= 4.3.0)

**Comment by JensFu** [comment]
This package downgrade is because the "nearest" version to the project wins. 
In this case your project (which also references log4net) references a lower version of the sockets than log4net does. Since the log4net reference is to the sockets is not "direct" it looses. The build detects this and warn about this.
I do not know exactly where the reference to the lower version of the socket package comes from (maybe from the default netcoreapp3.0 dependencies). 
You can easily solve this by adding the higher version of the socket reference directly (in the same project as your log4net reference is added). Be aware that this might not solve all your version conflicts, so adding a meta package might be the better choice.

Try adding the latest (3.0.0) version of Microsoft.NETCore.Targets package.

Not sure if this is the only and best solution. But it feels much better than supressing the warning, which is supposed in many forums.

**Comment by IqraMunir5** [comment]
Thanks a lot. Adding Microsoft.NETCore.Targets v3.0.0 nuget package in my project resolved the issue.
