### ISSUE TITLE
Double printing message

### ISSUE THREAD

**Issue by wjdavis5** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#62]
I'm seeing some strange behavior where messages are being double printed:

//start of json log
{"appName":"PvaTest","level":"ERROR","messageObject":"test","renderedMessage":"test","timestampUtc":"2019-02-21T17:37:44.1051799Z","logger":"test","thread":"1","exceptionObject":{"ClassName":"System.Exception","Message":"test","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":null,"RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":null,"WatsonBuckets":null},"exceptionObjectString":"System.Exception: test","userName":"a\\a","domain":"PvaTest.exe","identity":"","pid":45700,"machineName":"45K9VT2","workingSet":23457792,"osVersion":"Microsoft Windows NT 6.2.9200.0","properties":{"log4net:UserName":"a\\a","log4net:Identity":"","CustomerId":3,"log4net:HostName":"45K9VT2"}} //end of json log
System.Exception: test // <---- where did this come from?

![image](https://user-images.githubusercontent.com/2580575/53189985-ae984900-35d6-11e9-8a5f-0b39d0220144.png)

I cant figure out where this is coming from. I've set a breakpoint in my layout class and when it writes to the TextWriter that value is not there, looks like maybe its being added by this Library?

I see the same thing using the standard pattern layout:
![image](https://user-images.githubusercontent.com/2580575/53190248-22d2ec80-35d7-11e9-8deb-05984ff28f54.png)

It seems to only do this when an exception is passed in.

If I set these to null it fixes the problem:
![image](https://user-images.githubusercontent.com/2580575/53190709-287d0200-35d8-11e9-9e43-6f089a3213c8.png)

Have you ever seen this?

**Comment by huorswords** [comment]
Hello @wjdavis5 ,

No, I hadn't seen this behavior before. In fact, on the little set of unit tests that the project have, I cannot reproduce de issue throwing an exception manually.

Unfortunately, I don't want to remove the exception parameter from the underlying call to log4net, because I think that I will broke some use cases.

I will take a look and perform some additional tests, and I will come back to you with some conclusions. 

Regards

**Comment by Lechus** [comment]
Double logging.
2019-03-05 17:29:53,615 [8] INFO  App  
 Request starting HTTP/1.1 DEBUG http://localhost:62403/  0 
 
2019-03-05 17:29:53,617 [7] INFO  App  
 Request starting HTTP/1.1 GET http://localhost:44353/api/leads   
 
2019-03-05 17:29:53,619 [8] INFO  App  
 Request starting HTTP/1.1 DEBUG http://localhost:62403/  0 
 
2019-03-05 17:29:53,626 [7] INFO  App  
 Request starting HTTP/1.1 GET http://localhost:44353/api/leads   
 
2019-03-05 17:29:53,663 [8] INFO  App  
 Request finished in 42.4969ms 200  
 
2019-03-05 17:29:53,664 [8] INFO  App  
 Request finished in 42.4969ms 200  
 
2019-03-05 17:29:53,778 [7] INFO  App  
 Request finished in 163.0507ms 404  
 
2019-03-05 17:29:53,779 [7] INFO  App  
 Request finished in 163.0507ms 404  

PS: How to disable INFO logs and other not triggered by code ,but by .NET Core?

**Comment by Mxw3** [comment]
Hello @wjdavis5 ,

Check your "log4net.config" file; does your layout pattern contain "%newline%exception" on the end?

All the best.
