### ISSUE TITLE
Can not find log4net.config when use Log4NetProviderOptions

### ISSUE THREAD

**Issue by futurify-ydang** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#63]
I Have followed the instruction in [https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore](url) to configure log4net for asp net core 2.2 project.

When I run I face this error
`Exception has occurred: CLR/System.IO.FileNotFoundException
An exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Could not find file 'D:\Source\WorkSpace\BlueSpatial\BSCore\BSWeb\bin\Debug\netcoreapp2.2\log4net.config'.'`

Anyone give me a help? Thanks

**Comment by huorswords** [comment]
Hello @futurify-ydang ,

Have you tried to set the log4net.config file as Copy Always / Copy if newer from Visual Studio?

**Comment by futurify-ydang** [comment]
Thanks @huorswords! It worked for me.
