### ISSUE TITLE
Log only custom messages

### ISSUE THREAD

**Issue by pantonis** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#65]
I have recently started to use Microsoft.Extensions.Logging.Log4Net.AspNetCore on asp.net core 2.2

I managed to successfully log my custom messages but I also see in log.txt that asp.net core events are written.
Is there any way to prevent this and just log my custom message only?

Thanks

**Comment by huorswords** [comment]
Hello @pantonis ,

Yes, you can use the built-in filtering system from Microsoft.Extensions.Logging library.

Example:
```csharp
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .ConfigureLogging((hostingContext, logging) =>
            {
                // Apply any desired filter here.
                logging.AddFilter("Microsoft", LogLevel.None);
            })
            .UseStartup<Startup>();
}
```
