### ISSUE TITLE
Missleading github repo and nuget package name

### ISSUE THREAD

**Issue by ajtowf** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#66]
The naming indicates that this repo is officially backed by Microsoft when in fact it's one person behind it.

**Comment by huorswords** [comment]
Hello @ajtowf,

I'm sorry to hear you about it, but at any moment I want to simulate that this project is supported by Microsoft. The naming of the nuget package only wants to indicate that is a package intended to be "compatible" within the Microsoft.Extensions.Logging official package.

Nowhere on the package indicates that the supporter is Microsoft (I will be happy that they contribute on it), neither in the repository. And every contributor has been included in the acknowledge section in the readme file.

At the other hand, this is a open source package, based on an Microsoft MVP idea on how to implement a Log Provider for Log4Net library, library that *officially is not supported* by Microsoft.

You are able to contribute to this repo whenever you want. And also able to not use it if you are not comfortable with it. I develop it on my free time, without expecting to get any profit more than contribute to the community.

Anyway, thank you by your comments.
