### ISSUE TITLE
Unable to use Log4Net in windows service

### ISSUE THREAD

**Issue by JocelyneElKhoury7** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#67]
I am using a windows service in ,net core and i tried to implement the library but it is not working i keep getting that ILogger is not register although i have added it in the services

**Comment by huorswords** [comment]
Hello @JocelyneElKhoury7 ,

Excuse me to answer you so late, but I'm very busy at my job and I don't have so much time on the last weeks.

Could you please provide a sample or some code in order to reproduce your issue?

It is difficult to me to reproduce your scenario from scratch.

Thank you.

**Comment by JocelyneElKhoury7** [comment]
Hello @huorswords,

I have fixed it and now it is logging, but i got another issue now, the same line is being logged several times, it turned out that because i have to set logger.AddLog4Net() in the constructor of every class, if i don't set it the logging won't work, and when i set it the same line is logged several times(the number of times i have initiated the  logger.AddLog4Net() ) can you help me plz? below is my code, note that i am using .net core windows service 2.2

 class Program
    {
        static void Main(string[] args)
        {
            ILoggerFactory loggerFactory = new LoggerFactory();
            ILogger<Program> logger;
            logger = loggerFactory.CreateLogger<Program>();
            loggerFactory.AddLog4Net();
            logger.LogInformation("Program.Main");
            try
            {
                var builder = new ConfigurationBuilder()
                                    .SetBasePath(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location))
                                  .AddJsonFile("appsettings.json");

                var configuration = builder.Build();
                StaticVariables.SqlConnStr = configuration["ReportingDbSqlCnx"];

                var serviceProvider = new ServiceCollection()
                    .AddLogging()
                    .AddMemoryCache()
                    .AddTransient<IGeneralDA, GeneralDA>()
                    .AddTransient<IGeneral, General>()
                    .BuildServiceProvider();

                serviceQuartz.StartJobs().GetAwaiter().GetResult();

                using (var service1 = new ReportingService(serviceQ))
                {
                    ServiceBase.Run(service1);
                }

            }
            catch (Exception ex)
            {
                logger.LogError(ex.ToString());
            }
           
        }
    }

the logs in the program class is logged once but in the other classes it is logged several times 

  public class Class1 : IClass1
    {
        private readonly IGeneral _general;
        private readonly ILogger<QuartzScheduler> _logger;

        public Class1(IGeneral general, ILoggerFactory loggerFactory)
        {
            _general = general;
            loggerFactory.AddLog4Net();
            _logger = loggerFactory.CreateLogger<Class1>();
        }

        public async Task Start()
        {
            try
            {
                _logger.LogInformation("Class1.Start.Started");
                
                _logger.LogInformation("Class1.Start.Ended");
            }
            catch (Exception se)
            {
                _logger.LogError(se.ToString());
            }
        }
}

i tried this also

    public Class1(IGeneral general, ILogger<Class1> logger)
        {
            _general = general;
            _logger = logger;
        }

but in this case the logger did not write in the file

**Comment by JocelyneElKhoury7** [comment]
ok i fixed it for whoever face it i fixed it in this line

        var serviceProvider = new ServiceCollection()
                    .AddLogging(configure => configure.AddLog4Net())

and i used this in all my classes

      public Class1(IGeneral general, ILogger<Class1> logger)
       {
            _general = general;
            _logger = logger;
       }

**Comment by taadis** [comment]
@JocelyneElKhoury7 I met the same problem. and you can commit a pull request...

**Comment by huorswords** [comment]
@JocelyneElKhoury7 thank you very much by updating the issue.

As far as I understand, your problem is solved and the root cause was an incorrect initialization, isn't it?

I'm happy to know that you already resolved it. 👍

**Comment by JocelyneElKhoury7** [comment]
@huorswords  yes it was solved with changing the initialization thank you
