### ISSUE TITLE
Populating values into LogicalThreadContext

### ISSUE THREAD

**Issue by notes2c** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#69]
Is there any way to populate values into LogicalThreadContext, and if so, any suggestion how to do that ?

**Comment by huorswords** [comment]
Hello @notes2c,

Thank you by opening your question here.

As you can see in the code (https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/blob/develop/src/Microsoft.Extensions.Logging.Log4Net.AspNetCore/Scope/Registers/Log4NetObjectScopedRegister.cs), the Log4NetScope implementation allows you to inject any string / collection / object value into your LogicalThreadContext.

To find out how to use the Scoped logging, please refer to https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/blob/develop/README.md#using-beginscope .

Let me know if you have any other questions regardless this topic.

Thank you again.
