### ISSUE TITLE
Use log4net configuration in host config file

### ISSUE THREAD

**Issue by MarshallMoorman** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#71]
I am trying to use your library in an existing project which already has the log4net configuration defined in the host applications config file.  In this case it is the web.config file of a WCF web application hosted in .Net 4.7.2.  It appears the only way to define the configuration with this library is to use the log4net.config file.  Is that correct or am I missing something?  I would really like to use this, but it won't be possible if the only configuration option is the log4net.config file.

````xml
<section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,Log4net" />
````
````xml
  <log4net>
    <root>
      <appender-ref ref="RollingFileAppender" />
    </root>
    <logger name="ProductionAlertLogger" />
    <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender">
      <param name="File" value="C:\logs\ServiceLog.txt" />
      <param name="AppendToFile" value="true" />
      <param name="RollingStyle" value="Composite" />
      <param name="DatePattern" value="yyyyMMdd" />
      <param name="MaxSizeRollBackups" value="10" />
      <param name="MaximumFileSize" value="10MB" />
      <layout type="log4net.Layout.PatternLayout">
        <param name="ConversionPattern" value="%date %5p (%c{1}-%t)(%X{USER}) %m%n" />
      </layout>
    </appender>
  </log4net>
````

**Comment by huorswords** [comment]
Hello @MarshallMoorman ,

Sad to say that you are right. Currently it is only possible to use this nuget package if you have separated log4net.config file.

I will try to include the option to load the log4net configuration from app.config / web.config, but it will not be immediate. I let the issue open until the improvement is in place.

Thank you again.

**Comment by huorswords** [comment]
Included in v.3.0.3.
