### ISSUE TITLE
Is LogTrace even possible?

### ISSUE THREAD

**Issue by Hondelyk** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#72]
Is it possible to log trace level events? I was trying my best to turn on the Trace level logging in my configuration by either in Program.cs:
```c#
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .ConfigureLogging((hostingContext, logging) =>
            {
                logging.SetMinimumLevel(LogLevel.Trace);
                logging.ClearProviders();
                logging.AddLog4Net();
            })
            .UseStartup<Startup>();
```
And in Startup.cs:
```c#
services.AddLogging(logging =>
            {
                logging.SetMinimumLevel(LogLevel.Trace);
                logging.ClearProviders();
                logging.AddLog4Net();
            });
```
And while debugging I am able to confirm, that LoggerFactory MinLevel is set to Trace, however:
```
_logger.IsEnabled(LogLevel.Trace);
``` 
Is always returning false and logging to trace is always ignored. I've read something about trace level in issue #44, but to be honest I did not understand the outcome regarding Trace level (sorry, English is not my native language).
So, is it even possible to log to trace or do I have to use rest of available logging levels?

**Comment by huorswords** [comment]
Hello @Hondelyk ,

Thank you very much by opening this question. I have been doing some tests on my side, and it is not a problem within this package itself, rather than configuration issues on Microsoft.Extensions.Logging side.

Let me give it a try, and I will be back with some answers, I hope.

Thank you & regards.

**Comment by Hondelyk** [comment]
Hi @huorswords ,

Thank you for looking into this. Were you able to look into this and possibly enable trace logging?

Thanks for your great work and regards.

**Comment by huorswords** [comment]
Hello @Hondelyk ,

I'm not forgetting about this issue, but I have not been able to find what it is happening, as the Trace messages are not written neither with the built-in providers for debug and console.

I'm investigating further. Sorry for the delay.

**Comment by Hondelyk** [comment]
Hi @huorswords ,

No worries, in project where I am using this extension I simply learned to less logging levels. Of course if you will find out how to turn on trace level I will be verry happy, but It's not the end of the world.

**Comment by huorswords** [comment]
Hi @Hondelyk,

My apologizes to be so late answering your question.

I think that I have finally found the way to log the Trace level messages. I have uploaded a branch with a working example: https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/tree/feature/72/samples/NetCoreApp2.0/WebApi

The problem have two causes:
1. When the log4net.config file doesn't indicate "ALL" or "TRACE" as Logging level, the Trace level is directly ignored. Reviewing the [log4net official documentation](https://logging.apache.org/log4net/release/sdk/index.html), seems that somehow "DEBUG" is a higher level than "TRACE".

```xml
<log4net>
        <!-- Your appenders here! -->
	<root>
		<level value="TRACE" />
                <!-- Your appenders references here! -->
	</root>
</log4net>
```
2. Additionally, you need to define de default log level (at Microsoft.Extensions.Logging level) to "TRACE".

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Trace",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}
```

After configuring it, you can now log TRACE level messages using your log4net appenders.

Please, let me know if the explanation fulfills your question.

Thank you again by your patience.

**Comment by Hondelyk** [comment]
Sorry for late response. Thank you very much! It does work perfectly now.
