### ISSUE TITLE
log4net not working for  .net core ihostedservice

### ISSUE THREAD

**Issue by yeibl** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#73]
Hi,huorswords! i got one question , when i use log4net  int the .net core  BackgroundService,it not working for we ,can you fix this !   the injected Logger is not log4net privoder  but Microsoft.Extensions.Logging logger ,i use it  for rabbitmq consumer
like this

 `	
public class OrderDelayMessageConsumer : ConsumerBase
	{

private ILogger _logger;
		public OrderDelayMessageConsumer(
			ILogger<OrderDelayMessageConsumer> logger,
			ShopDropRepository shopDropRepository
			)
		{
			_logger = logger;
			_shopDropRepository = shopDropRepository;
		}
`

`public override bool Proccess(string roulekey, string message)
{

			_logger.LogDebug(message);
			_logger.LogError(message);
}
}
`
the class OrderDelayMessageConsumer  inherit  Microsoft.Extensions.Hosting.BackgroundService
class     information here [https://docs.microsoft.com/zh-cn/dotnet/api/microsoft.extensions.hosting.backgroundservice?view=dotnet-plat-ext-3.0](url)

Hope you can answer, thank you very much!

**Comment by huorswords** [comment]
Hello @yeibl ,

Thank you by opening this issue, and sorry to be so late to answer you.

I have been testing your scenario, and, if I am not missing something, in my case, the log4net logging appenders are working. I have uploaded a working sample into [this folder](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/tree/feature/73/samples/Sample.HostedService/Sample.HostedService), written for NET Core 3.0 and using a default simple worker that only writes a message into loggers each second.

Could you review it to check if you are missing some configuration or maybe there is another scenario that I have not identified?

Thank you.

**Comment by AleRoe** [comment]
Hi huorswords!

while not directly related, could you please update and test your working sample using the UdpAppender. I'm using the configuration below in a .net core 3 app but the UdpAppender ist not sending any data (verified using LiveTcpUdpWatch). The same configuration works fine under .net framework 4.7.2. I'm not sure if the is related to the UdpAppender implementation or the Logging.Extensions. Would be great if you could investigate!

<appender name="UdpAppender" type="log4net.Appender.UdpAppender">
    <remoteAddress value="127.0.0.1" />
    <remotePort value="7073" />
    <layout type="log4net.Layout.XmlLayoutSchemaLog4j" />
  </appender>

Thanks
Alexander

**Comment by huorswords** [comment]
Hello @AleRoe ,

I have uploaded the configuration file to include an UdpAppender logger and it works as expected, verifying it through Wireshark.

**Comment by AleRoe** [comment]
Hi again,

sorry, but I can't seem to find your modified configuration file.
The ones in the samples don't referenece UdpAppender.
Am I overseeing something?

Cheers
Alexander

**Comment by huorswords** [comment]
Hi,

It is located on the [log4net.config](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/blob/feature/73/samples/Sample.HostedService/Sample.HostedService/log4net.config) file on respective branch.

Please, let me know if everything it's ok.

**Comment by AleRoe** [comment]
Hi huorswwords,

apologies for the late response.
I can confirm that it works when I use the configuration settings from your sample.
The difference is that your are using the layout type "log4net.Layout.PatternLayout", whereas I am using the "log4net.Layout.XmlLayoutSchemaLog4j" which for some reason does not seem to work under .net core.
I will investigate further.
Thank you very much for your time!

Cheers
Alexander

**Comment by AleRoe** [comment]
Seems to be a known issue:
https://issues.apache.org/jira/browse/LOG4NET-586
https://stackoverflow.com/questions/44650389/log4net-layout-xmllayout-does-not-create-logs-in-net-core-platform

**Comment by huorswords** [comment]
@yeibl any update on this? Could you update about your scenario or confirm that the example background service is working for you?

**Comment by AleRoe** [comment]
Hi again,

the problem seems to be twofold.
Under .net core, "log4net.layout.xmllayout" uses a XmlTextWriter that does not allow colons ":" in Element names. By default, Xmllayout uses "log4net" as the element prefix which will cause an exception. The way to get around this is by setting the prefix to "" in log4net.config.

Then there seems to be a general issue with the UdpAppender which uses conditional compiler constants when creating the UdpClient. The current code does not cater for .netcore though. And although Udp packets are sent, they are not recognized as UDP/XML packets by Wireshark. Instead the protocol is SKYPE and the data is not formatted properly. I'm currently looking into this in more detail and can provide you with more details if you like.

**Comment by huorswords** [comment]
Sure @AleRoe! Keep us posted, please. 😄

**Comment by AleRoe** [comment]
Hello @huorswords,

it turned out that this is an encoding issue.
log4net.Appender.UpdAppender uses Unicode encoding by default when running under netcoreapp3.0. The issue can be fixed easily by derving from UdpAppender and setting the correct encoding. 
Details and sample code can be found here: 
https://github.com/AleRoe/Log4netUdpAppenderNetCore 

Hope this helps.

**Comment by chenghehe** [comment]
> Hello @yeibl ,
> 
> Thank you by opening this issue, and sorry to be so late to answer you.
> 
> I have been testing your scenario, and, if I am not missing something, in my case, the log4net logging appenders are working. I have uploaded a working sample into [this folder](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/tree/feature/73/samples/Sample.HostedService/Sample.HostedService), written for NET Core 3.0 and using a default simple worker that only writes a message into loggers each second.
> 
> Could you review it to check if you are missing some configuration or maybe there is another scenario that I have not identified?
> 
> Thank you.

[This example](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/tree/feature/73/samples/Sample.HostedService/Sample.HostedService)
Invalid in .Net Core 3.1.1。
I want to use. Net core 3.1 to create a secondary service as a Windows service. When I want to use log4net for logging, I will configure it according to your example, and finally find it doesn't work!!

`<?xml version="1.0" encoding="utf-8"?>
<log4net>
  
  <appender name="Console" type="log4net.Appender.ConsoleAppender">
    <layout type="log4net.Layout.PatternLayout">
      
      <conversionPattern value="%date %5level %logger.%method [%line] - %property{scope} %property{test} MESSAGE: %message%newline %exception" />
    </layout>
  </appender>

  <appender name="Error" type="log4net.Appender.RollingFileAppender" >
    <param name="File" value="D://Log4nets/mqWorkerService/Error" />
    
    <appendToFile value="true" />
    <maximumFileSize value="500kb" />
    <param name="RollingStyle" value="Size" />
    <Encoding value="UTF-8" />
    <maxSizeRollBackups value="3" />
    <lockingModel type="log4net.Appender.FileAppender+MinimalLock" />
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%level [%date] (%file:%line) - %message%newline" />
    </layout>
    <filter type="log4net.Filter.LevelRangeFilter">
      <param name="LevelMin" value="ERROR" />
      <param name="LevelMax" value="FATAL" />
    </filter>
  </appender>


  <appender name="ConsoleAppender" type="log4net.Appender.ManagedColoredConsoleAppender">
    <mapping>
      <level value="ERROR" />
      <foreColor value="Red" />
    </mapping>
    <mapping>
      <level value="WARN" />
      <foreColor value="Yellow" />
    </mapping>
    <mapping>
      <level value="INFO" />
      <foreColor value="White" />
    </mapping>
    <mapping>
      <level value="DEBUG" />
      <foreColor value="Green" />
    </mapping>
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%date %5level %logger.%method [%line] - %property{scope} %property{test} MESSAGE: %message%newline %exception" />
    </layout>
  </appender>

  <root>
    <level value="DEBUG" />
    <appender-ref ref="Error" />
    <appender-ref ref="ConsoleAppender" />
  </root>
</log4net>

`
In asp.net core webapi, it is possible! Invalid in ihostedservice!

**Comment by AleRoe** [comment]
Hi @chenghehe,

My application uses both WebApi and ihostedservice under .net core 3.1 and logging works just fine using the extension, so I would assume this is some kind of configuration issue.
Have you tried activating debugging output using <log4net debug=" true">?
This might shed some light on your issue.
Regards
Alexander

**Comment by omrumcetin** [comment]
Below error happened to me, its not accepting ":" in log4j:event 
`System.ArgumentException: Invalid name character in 'log4j:event'. The ':' character, hexadecimal value 0x3A, cannot be included in a name.
   at System.Xml.XmlWellFormedWriter.CheckNCName(String ncname)
   at System.Xml.XmlWellFormedWriter.WriteStartElement(String prefix, String localName, String ns)
   at log4net.Layout.XmlLayoutSchemaLog4j.FormatXml(XmlWriter writer, LoggingEvent loggingEvent)
   at log4net.Layout.XmlLayoutBase.Format(TextWriter writer, LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.RenderLoggingEvent(TextWriter writer, LoggingEvent loggingEvent)
   at log4net.Appender.TextWriterAppender.Append(LoggingEvent loggingEvent)
   at log4net.Appender.FileAppender.Append(LoggingEvent loggingEvent)
   at log4net.Appender.RollingFileAppender.Append(LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.DoAppend(LoggingEvent loggingEvent)
2020-05-29 20:04:01,279 INFO EricssonBcgCmExportInvokerLite.Program - Connecting to config FILL_HERE
2020-05-29 20:04:03,691 FATAL EricssonBcgCmExportInvokerLite.Program - Rebex.Net.SshException: Unable to resolve hostname.`
