### ISSUE TITLE
Dependency on Core 2.2.x even for Net Core 2.0 and 2.1?

### ISSUE THREAD

**Issue by Lechus** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#74]
HI,
Since version 2.2.11 you changed dependencies to version 2.2.x even for Net Core 2.0 and 2.1?
.NETCoreApp 2.0
log4net (>= 2.0.8)
Microsoft.Extensions.Configuration (>= **2.2.0**)
Microsoft.Extensions.Configuration.Abstractions (>= 2.2.0)
Microsoft.Extensions.Configuration.Binder (>= 2.2.4)
Microsoft.Extensions.Logging (>= 2.2.0)
System.Xml.XPath.XDocument (>= 4.3.0)
.NETCoreApp 2.1
log4net (>= 2.0.8)
Microsoft.Extensions.Configuration (>= **2.2.0**)
Microsoft.Extensions.Configuration.Abstractions (>= 2.2.0)
Microsoft.Extensions.Configuration.Binder (>= 2.2.4)
Microsoft.Extensions.Logging (>= 2.2.0)
System.Xml.XPath.XDocument (>= 4.3.0)
.NETCoreApp 2.2
log4net (>= 2.0.8)
Microsoft.Extensions.Configuration (>= 2.2.0)
Microsoft.Extensions.Configuration.Abstractions (>= 2.2.0)
Microsoft.Extensions.Configuration.Binder (>= 2.2.4)
Microsoft.Extensions.Logging (>= 2.2.0)
System.Xml.XPath.XDocument (>= 4.3.0)

any chance to get it back pointing to the the same 2.x.x as it was in 2.10.0 ?

**Comment by huorswords** [comment]
Hello @Lechus, 

Thank you for opening this issue.

I will update the next version to refer to 2.0.* and 2.1.* for netcoreapp2.0 and netcoreapp2.1 target frameworks.

**Comment by huorswords** [comment]
Included in v.3.0.3
