### ISSUE TITLE
Dont throw when LogLevel is None

### ISSUE THREAD

**Issue by AndreMantas** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#75]
In [this switch](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/blob/develop/src/Microsoft.Extensions.Logging.Log4Net.AspNetCore/Log4NetLogger.cs#L68), the level `None` is not being supported and an exception is thrown.

In this case I think it should return false as None shouldn't log anything.

`None` is a valid LogLevel, see [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=dotnet-plat-ext-3.0)

**Comment by huorswords** [comment]
Hello @AndreMantas ,

Thank you by opening this issue. I agree with you, I only should ignore the message without throwing an exception.

This fix will be implemented on the next release.

Thank you!

**Comment by huorswords** [comment]
Included in version 3.0.3.
