### ISSUE TITLE
NET Core 3.0 - Logging debug level messages

### ISSUE THREAD

**Issue by gusgorman** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#76]
I have followed the instructions here: https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#net-core-20---logging-debug-level-messages in core 3.0 app, but I have only getting WARN and ERROR level logging.

Bizarrely though, there is a load of Microsoft.AspNetCore INFO stuff coming through.

Does this make sense? Do I need to do something different with Core 3.0?

This is my CreateWebHostBuilder method. It was actually initially created by a colleague, and I have just noticed the signature is different from that in the example linked to above (ie it returns IWebHostBuilder instead of IWebHost)

```
         public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration((ctx, builder) =>
            {
                builder.AddJsonFile("appsettings.json", false, true);
                builder.AddJsonFile($"appsettings.{Environment.MachineName}.json", true, true);
            })
            .CaptureStartupErrors(true)
            .UseSetting("detailedErrors", "true")
            .UseStartup<Startup>()
            .ConfigureLogging((hostingContext, logging) =>
            {
                // The ILoggingBuilder minimum level determines the
                // the lowest possible level for logging. The log4net
                // level then sets the level that we actually log at.
                logging.AddLog4Net();
                logging.SetMinimumLevel(LogLevel.Debug);          
            })
```

**Comment by huorswords** [comment]
Hello @gusgorman ,

I have tested a HostedService sample ([here](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/tree/feature/73/samples/Sample.HostedService)) modifying it as follows...

*Startup.cs*
```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
	Host.CreateDefaultBuilder(args)
		.ConfigureServices((hostContext, services) =>
		{
			services.AddLogging();
			services.AddHostedService<Worker>();
		})
		.ConfigureLogging(configureLogging =>
		{
			configureLogging.SetMinimumLevel(LogLevel.Debug); // <-- Added
			configureLogging.AddLog4Net();
		});
```
... and...

*Worker.cs*
```csharp
    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;

        public Worker(ILogger<Worker> logger)
        {
            _logger = logger;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                _logger.LogDebug("DBG: Worker running at: {time}", DateTimeOffset.Now); //<--- Added
                await Task.Delay(1000, stoppingToken);
            }
        }
    }
```

After start the service, the resulting logged data includes the _DBG_ messages.

Maybe it is a problem within the level you set up on your appender configuration on log4net.config file:

```xml
  <root>
    <level value="DEBUG" />
    <appender-ref ref="RollingFile" />
    <appender-ref ref="TraceAppender" />
    <appender-ref ref="ConsoleAppender" />
    <appender-ref ref="UdpAppender" />
  </root>
```

**Comment by gusgorman** [comment]
Hello @huorswords 

Thankyou for looking at this. It appears I have something very weird going on!

My appender configuation is as follows:

```
	<root>
		<level value="All" />
		<appender-ref ref="RollingFileAppender" />
		<appender-ref ref="NHibernateFileLog" />
	</root>
```

I have added a few lines of logging to a Razor page as follows:

```
            _logger.LogInformation("Testing logger info.....");
            _logger.LogTrace("Testing logger trace.....");
            _logger.LogDebug("Testing logger debug.....");
            _logger.LogWarning("Testing logger warning.....");
            _logger.LogError("Testing logger error.....");
```

The resulting NHIbernate log contains both DEBUG and INFO level messages. The RollingFile log mysteriously does contain the Microsoft.AspNetCore INFO level messages, but only the WARN and ERROR messages that I am logging myself. 

```
2019-12-16 10:10:27,256 INFO  Microsoft.AspNetCore.Authorization.DefaultAuthorizationService - Authorization was successful.
2019-12-16 10:10:27,276 INFO  Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker - Executing handler method RoleModel.Web.Pages.Users.Index.OnGet - ModelState is Valid
2019-12-16 10:10:27,280 WARN  RoleModel.Web.Pages.Users.Index - Testing logger warning.....
2019-12-16 10:10:27,280 ERROR RoleModel.Web.Pages.Users.Index - Testing logger error.....
2019-12-16 10:10:27,587 INFO  Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker - Executed handler method OnGet, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.
2019-12-16 10:10:27,923 INFO  Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker - Executed page /Users/Index in 666.6563ms
```

**Comment by huorswords** [comment]
Hello @gusgorman ,

Very sorry by not answering you until now.

Please, could you check the conclusions on the #72 issue, as is related also to the missing Trace level and could be the same issue that you are experiencing?

Thank you. Let me know if it solves your problem, please. :)

**Comment by YeMing-Zhang** [comment]
public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging =>
                {
                    logging.AddLog4Net()AddFilter("{namespace}", LogLevel.Debug);
                    
                })

                .ConfigureWebHostDefaults(
                    webBuilder => { webBuilder.UseStartup<Startup>(); });
        }

**Comment by YeMing-Zhang** [comment]
```
        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.AddLog4Net().AddFilter("{namespace}", LogLevel.Debug);
                })

                .ConfigureWebHostDefaults(
                    webBuilder => { webBuilder.UseStartup<Startup>(); });
        }
```

**Comment by gusgorman** [comment]
> Hello @gusgorman ,
> 
> Very sorry by not answering you until now.
> 
> Please, could you check the conclusions on the #72 issue, as is related also to the missing Trace level and could be the same issue that you are experiencing?
> 
> Thank you. Let me know if it solves your problem, please. :)

Hi @huorswords 

Sorry I realised the client wanted us to use serilog in the web app I was setting up, so I'm not using this package there anymore.  However, I have since installed this  package in a console app and don't have a problem.

Thanks for the reply and sorry I can't provide any more useful info

**Comment by huorswords** [comment]
No problem. Let's close this issue then.

Thank you @gusgorman !

**Comment by tgillitzer** [comment]
I had a similar issue with this.   After trying all of the variations of different things I found here and other places, it turned out the Logging.LogLevel.Default value is in both appsettings.json and appsettings.Development.json.   If you are building Debug, you have to change both.   Simple/obvious, yes, but I fought with it all day, so posting this in case it helps someone else.

**Comment by verzada** [comment]
> I had a similar issue with this. After trying all of the variations of different things I found here and other places, it turned out the Logging.LogLevel.Default value is in both appsettings.json and appsettings.Development.json. If you are building Debug, you have to change both. Simple/obvious, yes, but I fought with it all day, so posting this in case it helps someone else.

Can confirm that the "appsettings.Development.json" overrides appSettings.json.
Either change the content in the development file or remove it entirely.
