### ISSUE TITLE
Does this depend on ASP.NET Core or just Core?

### ISSUE THREAD

**Issue by gusgorman** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#78]
Hello,
Sorry not sure if this is the correct place to ask this, but  I couldn't find a message option.

Does this package actually depend on Asp.NetCore or would it work fine in a Core Console App?

thanks!

**Comment by huorswords** [comment]
Hello @gusgorman ,

Thank you by being interested in this package.

Currently, this package is depending on Microsoft.Extensions.Logging library, that is the default logging system for ASP.Net core, but is not strictly bounded to it. You can use Microsoft.Extensions.Logging library on your console app. :)

Hope it helps.

**Comment by gusgorman** [comment]
Hello @huorswords 
Great thanks!
I've just tried it and it works perfectly

**Comment by ArveSystad** [comment]
Was going to add a similar issue; I had to double check the dependencies (if it was going to pull in ASPNETCore, for example) before installing it. So it looks to be OK, but the name is a bit misleading. 

Perhaps a name change could be considered for the future? Seems reasonable given the popularity of log4net. As of now it immediately looks like it somehow depends on Asp.net core, and would therefore not fit in a normal console app/worker service app. Or perhaps even just double-publish without the "aspnetcore" name to provide a smooth transition?
