### ISSUE TITLE
log4net %method is not logging the method name.

### ISSUE THREAD

**Issue by priyesh1193** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#80]
Hi 
I am using this package  - Microsoft.Extensions.Logging.Log4Net.AspNetCore -Version 3.1.0  in my asp.net core 2.1 application
**I have an issue like log4net %method is not logging the method name.
Method name =  ? (method name value is coming as ? )** in my log file.

I am using log4net.Appender.RollingFileAppender
and my conversion pattern of log4net.config is 

conversionPattern value="%method" 

I tried with %M also.

**Comment by huorswords** [comment]
Hello @priyesh1193,

I'm sorry, but I'm very busy on last months and I am not able to answer opened issues as fast as I want.

This project is only a connector within Log4net library and Microsoft.Extensions.Logging subsystem. All the appenders, and the log4net itself, are mantained by another team / people.

Could you try to reproduce your issue directly with log4net library, without using this extension project? If not, let me know what you did and I will try to setup an scenario trying to debug the problem if it really belongs to this nuget package.

Thank you. I will wait for your answer.
