### ISSUE TITLE
Log4NetProviderOptions.OverrideCriticalLevelWith does not work

### ISSUE THREAD

**Issue by WilsonPan** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#83]
when Log4NetProvider.CreateLogger(string categoryName) is called，there will be call CreateLoggerImplementation，this functions will new the Log4NetProviderOptions , but not set Log4NetProviderOptions.OverrideCriticalLevelWith

**Comment by huorswords** [comment]
Will be included on the next release. Thank you very much by your PR. :)
