### ISSUE TITLE
Trace Level Logging

### ISSUE THREAD

**Issue by benjstern** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#85]
I recently ran into an issues where i couldn't get Trace and Debug level logging when using this extension and requires a modification in the "appsettings.Development.json" where i had been mistakenly modifying it in the "appsettings.json"

{
  "Logging": {
    "LogLevel": {
      "Default": "Trace",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}

This should be added to a faq of some other part of the Readme so new users can quickly understand that also this needs to be added for development testing if they want Debug/Trace level logs.

I only later found it when stumbling over this post: https://stackoverflow.com/a/52077217/1190540

**Comment by huorswords** [comment]
Hello @benjstern ,

Thank you by your suggestion. Do you want to update the documentation and make a PR in order to include this information?

For sure, you can write it better than me, as you already have experienced this issue and could give some context.

Thank you.

**Comment by huorswords** [comment]
Thank you very much @benjstern . Merged. I will update the master branch with the other pending changes soon.

**Comment by benjstern** [comment]
@huorswords thank you for your assistance.
