### ISSUE TITLE
Signed assembly

### ISSUE THREAD

**Issue by cerebrate** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#9]
I'd like to use this package in a couple of projects but am unable to, since it would need to be called by a signed assembly and is itself unsigned. Could you stick a signing key on there, perchance?

Thanks.

**Comment by huorswords** [comment]
Hello @cerebrate ,

Thank you very much by using this library.

I just uploaded a new nuget package with version 2.0.2 (and related code here on github) in order to provide you a strong name signed assembly.

Please, come back to me if you have any concerns or comments.

Thank you. Regards.
